### PR TITLE
Restrict fluentd version explicitly

### PR DESCRIPTION
**Pull request by kenhys**
This is officially recommended way but undocumented.

### CODE REVIEW

**Comment by kou** [comment]
We can't confirm "undocumented" is official recommendation. Please remove "< 2".

**Comment by cosmo0920** [comment]
This plugin seems to be frequently updated.
We can remove Fluentd version upper bound.

**Comment by kenhys** [comment]
I've removed upper bound.

**Comment by kou** [comment]
Merged.

**Pull request merged**
